using UnityEngine;

[RequireComponent(typeof(SpriteRenderer))]
public class HandleColorChanger : MonoBehaviour
{
    public Handle handle;
    public Color normalColor = Color.white;
    public Color attackColor = Color.red;
    public Color readyToFireColor = Color.yellow; // ”­ËğŒ‚ğ–‚½‚µ‚½‚Æ‚«‚ÌF

    private SpriteRenderer sr;

    void Start()
    {
        sr = GetComponent<SpriteRenderer>();
    }

    void Update()
    {
        if (handle == null) return;

        if (handle.isAttacking)
        {
            // ”­ËğŒ‚ğ–‚½‚µ‚Ä‚¢‚éê‡‚Í‰©F‚É
        }
        else
        {
            sr.color = normalColor;
        }
    }
}
